### ISSUE TITLE
multiclass dataset

### ISSUE THREAD

**Issue by rawiasammout** [felix-last/kmeans_smote#1]
your proposed hybrid approach is it applicable for multiclass dataset?

**Comment by felix-last** [comment]
Oversampling more than two classes is not currently possible.

**Comment by rawiasammout** [comment]
Thanks for your quick answer i am working on a multiclass imbalanced dataset and i am trying to balance it wit SCUT https://www.researchgate.net/publication/301453161_SCUT_Multi-Class_Imbalanced_Data_Classification_using_SMOTE_and_Cluster-based_Undersampling
But i've faced some problem in implementation because no further details about the strategy implemented .

**Comment by rawiasammout** [comment]
If you're ready we can collaborate together and propose a new hybrid technique to overcome multiclass data

**Comment by felix-last** [comment]
Thank you, but I'm not interested at the moment. In the future, multi-class support may be added to k-means SMOTE.

**Comment by felix-last** [comment]
Multi-class support is now available with release 0.1.0.

**Comment by rawiasammout** [comment]
Thanks Felix where can i find it and do you have any description of your extension

**Comment by felix-last** [comment]
@rawiasammout, you can simply `pip install kmeans-smote` as shown in the readme. The latest version (0.1.0) implements the multi-class case. 

To use kmeans-smote on multi-class data, there is nothing special to consider, just call `fit_sample` on your multi-class data and tune the algorithm's hyperparameters (see [docs](https://kmeans-smote.readthedocs.io/en/latest/)) to your needs. There is also a [small test](https://github.com/felix-last/kmeans_smote/blob/master/test/test_kmeans_smote.py#L163-L173) implemented to oversample a multi-class toy dataset.

From an algorithmic perspective, the second step of the algorithm (see readme > about) is repeated for each minority class. The paper referenced in the readme should provide you with a thorough explanation of how the algorithm works for the binary case - the multi-class case is only a small modification.
