### ISSUE TITLE
kmeans_smote test

### ISSUE THREAD

**Issue by hqulhtl** [felix-last/kmeans_smote#10]
Why didn't I get the visualization after running the test program? I only got the results in the example, but there was no visualization after test_kemans_smote.py

**Comment by felix-last** [comment]
The tests have a plot parameter which must be set to true if plots are desired.

**Comment by hqulhtl** [comment]
Hello, can you tell me?how to run test_kmeans_smote.py,and how to  call those test functions, I have already said that the value of the  plot is changed to True, but the result is the following  error.

---------------------------------------------------------------------------
 
TypeError                                 Traceback (most recent call last)
  in 
 ----> 1 test_smoke(True)
 
 in test_smoke(plot)
 48
 49     """Execute k-means SMOTE with default parameters"""
 ---> 50     kmeans_smote = KMeansSMOTE(random_state=RND_SEED)
 51     X_resampled, y_resampled = kmeans_smote.fit_sample(X, Y)
 52
 
TypeError: Can't instantiate abstract class KMeansSMOTE with abstract methods _sample



------------------ 原始邮件 ------------------
发件人: "Felix Last"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 凌晨1:03
收件人: "felix-last/kmeans_smote"<kmeans_smote@noreply.github.com>;
抄送: "李海滔"<2516073152@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [felix-last/kmeans_smote] kmeans_smote test (#10)




The tests have a plot parameter which must be set to true if plots are desired.
