### ISSUE TITLE
Installation for Python2 fails

### ISSUE THREAD

**Issue by nakumgaurav** [felix-last/kmeans_smote#5]
It seems that the latest version is not compatible with Python2:

![image](https://user-images.githubusercontent.com/22325652/52591445-f6e29900-2e69-11e9-97ee-51ab5ae11892.png)

Clearly, Python2's open() function does not have the argument 'encoding', which causes the error in installation. Is there any previous version of the library compatible with python2?

**Comment by nakumgaurav** [comment]
Got it. That argument needed to be removed. For others encountering this issue:
1. clone the repo
2. Go to setup.py and remove the 'encoding' argument from the line shown in the image above.
3. pip install .
and you are done!

**Comment by felix-last** [comment]
Glad you figured it out. Thank you for sharing your advice with others!
